# Generated by Django 3.2.6 on 2024-07-13 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Level', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_code', models.CharField(default='2047c3f', editable=False, max_length=256)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('path_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('not_started', 'Not Started')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Level.level')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPathTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('topic_description', models.TextField()),
                ('topic_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('not_started', 'Not Started')], max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningPath.learningpath')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPathActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('activity_description', models.TextField()),
                ('activity_type', models.CharField(choices=[('video', 'Video'), ('quiz', 'Quiz'), ('assessment', 'Assessment'), ('assignment', 'Assignment'), ('discussion', 'Discussion'), ('reading', 'Reading'), ('exercise', 'Exercise'), ('project', 'Project'), ('lab', 'Lab')], default='video', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('questions', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningPath.learningpathtopic')),
            ],
        ),
    ]
