# Generated by Django 3.2.6 on 2024-07-13 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6be679f9-65bd-4d00-8bb6-00692a61a7fe'), editable=False, unique=True),
        ),
    ]
