# Generated by Django 3.2.6 on 2024-07-13 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0002_alter_account_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('25954c38-0608-4627-9c3a-730f474b3d4f'), editable=False, unique=True),
        ),
    ]
