# Generated by Django 3.2.6 on 2024-07-13 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LearningPath', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_style', models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('kinesthetic', 'Kinesthetic')], max_length=50, null=True)),
                ('quiz_scores', models.JSONField(blank=True, default=dict)),
                ('assessment_results', models.JSONField(blank=True, default=dict)),
                ('interests', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('completed_topics', models.ManyToManyField(blank=True, to='LearningPath.LearningPathTopic')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Level.level')),
                ('preferred_topics', models.ManyToManyField(blank=True, related_name='preferred_by', to='LearningPath.LearningPath')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
